# Dados das progressões (inline para facilitar deploy)

PROGRESSOES_PISTA_TRILHA = {
    1: {"area": "Físico", "desc": "Participar de pelo menos cinco atividades de patrulha ao ar livre"},
    2: {"area": "Físico", "desc": "Conhecer e aplicar normas de limpeza no tratamento e conservação de alimentos"},
    3: {"area": "Físico", "desc": "Aferir seu passo duplo e conhecer as medidas de seu corpo"},
    4: {"area": "Físico", "desc": "Conhecer os elementos que compõem a Caixa de Primeiros Socorros"},
    5: {"area": "Físico", "desc": "Conhecer as ações iniciais em acidentes e cuidar de ferimentos leves"},
    6: {"area": "Físico", "desc": "Aplicar medidas de segurança nas atividades de patrulha e Tropa"},
    7: {"area": "Físico", "desc": "Saber prevenir os males da exposição ao sol"},
    8: {"area": "Físico", "desc": "Manter hábitos de higiene individual e cuidado com uniforme"},
    9: {"area": "Físico", "desc": "Classificar o lixo e tratar resíduos de acampamentos"},
    10: {"area": "Físico", "desc": "Participar da manutenção do canto de patrulha"},
    11: {"area": "Físico", "desc": "Montar mochila para acampamento de 3 dias"},
    12: {"area": "Físico", "desc": "Montar cardápio de jornada com refeições equilibradas"},
    13: {"area": "Físico", "desc": "Colaborar na elaboração de alimentos em atividades"},
    14: {"area": "Físico", "desc": "Montar solução para purificação de água"},
    15: {"area": "Físico", "desc": "Utilizar diversos tipos de fogos de acampamento"},
    16: {"area": "Físico", "desc": "Organizar seu tempo com agenda"},
    17: {"area": "Físico", "desc": "Realizar tarefas escolares no prazo"},
    18: {"area": "Físico", "desc": "Frequentar regularmente atividades da patrulha e tropa"},
    19: {"area": "Físico", "desc": "Realizar regularmente atividade física ou esporte"},
    20: {"area": "Físico", "desc": "Participar de jogos respeitando regras e participantes"},
    
    21: {"area": "Intelectual", "desc": "Traçar e seguir sinais de pista"},
    22: {"area": "Intelectual", "desc": "Utilizar mapa e bússola para orientar-se"},
    23: {"area": "Intelectual", "desc": "Aplicar técnicas de tocaia em jogos"},
    24: {"area": "Intelectual", "desc": "Explorar a comunidade identificando problemas"},
    25: {"area": "Intelectual", "desc": "Estimar altura e distâncias"},
    26: {"area": "Intelectual", "desc": "Ler livro e apresentar resumo"},
    27: {"area": "Intelectual", "desc": "Utilizar técnica de previsão do tempo"},
    28: {"area": "Intelectual", "desc": "Participar de Jogos Democráticos"},
    29: {"area": "Intelectual", "desc": "Participar do Conselho de Patrulha"},
    30: {"area": "Intelectual", "desc": "Participar do planejamento de excursão"},
    31: {"area": "Intelectual", "desc": "Avaliar atividades com a patrulha"},
    32: {"area": "Intelectual", "desc": "Utilizar especialidades conquistadas"},
    33: {"area": "Intelectual", "desc": "Ajudar escoteiro a conquistar especialidade"},
    34: {"area": "Intelectual", "desc": "Participar de fogo de conselho"},
    35: {"area": "Intelectual", "desc": "Construir instrumento musical com sucata"},
    36: {"area": "Intelectual", "desc": "Conhecer e cantar canções tradicionais"},
    37: {"area": "Intelectual", "desc": "Ler e escrever mensagens em código secreto"},
    38: {"area": "Intelectual", "desc": "Utilizar rádio comunicador"},
    39: {"area": "Intelectual", "desc": "Montar blog ou projeto de comunicação"},
    40: {"area": "Intelectual", "desc": "Participar da construção de pioneirias"},
    41: {"area": "Intelectual", "desc": "Saber utilizar ferramentas de patrulha"},
    42: {"area": "Intelectual", "desc": "Participar da construção de Fogão Suspenso"},
    
    43: {"area": "Caráter", "desc": "Propor objetivos para melhorar aspectos da vida"},
    44: {"area": "Caráter", "desc": "Participar da avaliação de progressão pessoal"},
    45: {"area": "Caráter", "desc": "Avaliar desempenho nos cargos de patrulha"},
    46: {"area": "Caráter", "desc": "Explicar significado da Lei e Promessa Escoteira"},
    47: {"area": "Caráter", "desc": "Participar de cerimônias com Símbolos Nacionais"},
    48: {"area": "Caráter", "desc": "Explicar o que significa ser leal"},
    49: {"area": "Caráter", "desc": "Aplicar conceito de lealdade"},
    50: {"area": "Caráter", "desc": "Participar como animador em acampamento"},
    51: {"area": "Caráter", "desc": "Conhecer histórias de superação"},
    52: {"area": "Caráter", "desc": "Respeitar decisões do Conselho de Patrulha"},
    53: {"area": "Caráter", "desc": "Ajudar a melhorar o Conselho de Patrulha"},
    54: {"area": "Caráter", "desc": "Participar da eleição do Monitor"},
    
    55: {"area": "Afetivo", "desc": "Pesquisar malefícios de drogas"},
    56: {"area": "Afetivo", "desc": "Contribuir na manutenção do Livro de Patrulha"},
    57: {"area": "Afetivo", "desc": "Participar de turno de ronda"},
    58: {"area": "Afetivo", "desc": "Registrar momentos da história pessoal"},
    59: {"area": "Afetivo", "desc": "Participar de debate sobre filme/documentário"},
    60: {"area": "Afetivo", "desc": "Participar de Assembleias"},
    61: {"area": "Afetivo", "desc": "Propor temas para debate"},
    62: {"area": "Afetivo", "desc": "Participar da avaliação de acampamento"},
    63: {"area": "Afetivo", "desc": "Auxiliar novo integrante da patrulha"},
    64: {"area": "Afetivo", "desc": "Convidar patrulha para reunião em casa"},
    65: {"area": "Afetivo", "desc": "Participar de atividades de igualdade"},
    66: {"area": "Afetivo", "desc": "Compartilhar tarefas domésticas"},
    67: {"area": "Afetivo", "desc": "Investigar sobre mulheres na história"},
    68: {"area": "Afetivo", "desc": "Participar de cerimônia com pais/responsáveis"},
    69: {"area": "Afetivo", "desc": "Participar de atividade com família"},
    70: {"area": "Afetivo", "desc": "Solicitar ajuda de familiares para capacitar patrulha"},
    
    71: {"area": "Social", "desc": "Investigar sobre defensores dos direitos humanos"},
    72: {"area": "Social", "desc": "Participar de atividades sobre Direitos Humanos"},
    74: {"area": "Social", "desc": "Colaborar para definição de metas da patrulha"},
    75: {"area": "Social", "desc": "Assumir e desempenhar cargo na patrulha"},
    76: {"area": "Social", "desc": "Participar das decisões do Conselho de Patrulha"},
    77: {"area": "Social", "desc": "Participar de Assembleia de Tropa"},
    78: {"area": "Social", "desc": "Estudar sobre organização do Escotismo Brasileiro"},
    79: {"area": "Social", "desc": "Conhecer Estrutura de um Grupo Escoteiro"},
    80: {"area": "Social", "desc": "Realizar boas ações"},
    81: {"area": "Social", "desc": "Participar de MUTCOM"},
    82: {"area": "Social", "desc": "Fazer croqui da área onde reside"},
    83: {"area": "Social", "desc": "Conhecer localização de serviços públicos"},
    84: {"area": "Social", "desc": "Participar de comemoração típica regional"},
    85: {"area": "Social", "desc": "Participar de Jantar Festivo"},
    86: {"area": "Social", "desc": "Pesquisar jogos típicos da região"},
    87: {"area": "Social", "desc": "Participar de evento cívico"},
    88: {"area": "Social", "desc": "Explicar significados da Flor de Lis"},
    89: {"area": "Social", "desc": "Conhecer história do Grupo Escoteiro"},
    90: {"area": "Social", "desc": "Participar de atividade distrital/regional"},
    91: {"area": "Social", "desc": "Participar de JOTI ou JOTA"},
    92: {"area": "Social", "desc": "Participar de atividade pela paz"},
    93: {"area": "Social", "desc": "Pesquisar sobre pessoas que trabalharam pela paz"},
    94: {"area": "Social", "desc": "Participar de projeto ambiental"},
    95: {"area": "Social", "desc": "Realizar levantamento de pegadas de animais"},
    96: {"area": "Social", "desc": "Participar de excursão urbana ecológica"},
    
    97: {"area": "Espiritual", "desc": "Fazer orações rotineiras"},
    98: {"area": "Espiritual", "desc": "Participar de celebrações religiosas"},
    99: {"area": "Espiritual", "desc": "Realizar reflexões em acampamentos"},
    100: {"area": "Espiritual", "desc": "Participar de serviço comunitário religioso"},
    101: {"area": "Espiritual", "desc": "Aplicar ensinamentos religiosos no dia-a-dia"},
    102: {"area": "Espiritual", "desc": "Apresentar relato de ensinamentos religiosos"},
    103: {"area": "Espiritual", "desc": "Participar da construção de espaço de reflexão"},
    104: {"area": "Espiritual", "desc": "Orar utilizando oração da Tropa/Patrulha"},
    105: {"area": "Espiritual", "desc": "Praticar a oração"},
    106: {"area": "Espiritual", "desc": "Organizar livreto de orações"},
    107: {"area": "Espiritual", "desc": "Conhecer confissões religiosas dos amigos"},
    108: {"area": "Espiritual", "desc": "Pesquisar sobre confissão religiosa diferente"}
}

# Nota: Item 73 não existe (pula do 72 para 74)

EMOJIS_AREAS = {
    "Físico": "💪",
    "Intelectual": "🧠",
    "Caráter": "❤️",
    "Afetivo": "🤝",
    "Social": "👥",
    "Espiritual": "✨"
}
